version: '3'
services:
  app:
    image: yiisoftware/yii2-php:7.1-apache #Use official Yii2 php package with required extensions
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: dustcrm
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON #Temporary workaround, because mariadb volume dont work proper way in win10 docker without this parameters.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db, test_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db
  redis:
    image: redis:latest
  #Tests section:
  test_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: dustcrm_basic_tests
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
#      volumes: # Uncomment this lines if you want store test database on host machine
#        - ./test_db:/var/lib/mysql