<?php
/**
 * Created by PhpStorm.
 * User: Rikipm
 * Date: 30.06.2019
 * Time: 3:13
 */

return [
    ['pattern'=>'<slug>', 'route'=>'<slug>/index'], //Delete /index from url of controllers generated by yii\helpers\Url::to()
];